n = 4
t = 1
deployer_address = "0x60D61f20F3E27AAE2e1ddA096aB364E339F1031d"
[[peers]]
id = 0
host = "hbmpc.peer0.io"
http_port = 8080
mpc_port = 7000
eth_address = "0xd9CF37a616D4F5C40E63832f43a8293CB43b2850"

[[peers]]
id = 1
host = "hbmpc.peer1.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x896e9BA9034826632BDdb700f066c81a697E39c1"

[[peers]]
id = 2
host = "hbmpc.peer2.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x58f04C340D20456CF4f9D5D5B7ae5c420A44Ee0E"

[[peers]]
id = 3
host = "hbmpc.peer3.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x42a6a07e29c88FFafd2A9598469f151a85fFA4Bb"

[eth]
rpc_host = "eth.blockchain.io"
rpc_port = 8545

[contract]
path = "~/.coordinator/contract.rl"
lang = "ratel"
name = "MpcCoordinator"
address = "0xC431477e47DAeb173e115eCee6A7C323DF6A4A2b"
