os: linux
dist: xenial
language: python
python: 3.7
sudo: true

services:
  - docker

env:
  global:
    - DOCS_DEPLOY_KEY_LABEL: 63cc0c40c9de

matrix:
  include:
    - env: BUILD=tests
    - env: BUILD=flake8
    - env: BUILD=docs

install:  .ci/travis-install.sh

script: .ci/travis-script.sh

after_success: .ci/travis-after-success.sh

deploy:
  skip_cleanup: true
  provider: script
  script: .ci/travis-publish-docs.sh
  on:
    branch: test-publish-docs-to-github-pages
    condition: '"${BUILD}" == *docs*'



#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  keep-history: true
#  local-dir: docs/_build/html
#  on:
#    all_branches: true
#    condition: $TRAVIS_BRANCH =~ ^dev|docs-deploy-test$
