os: linux
dist: bionic
language: python
cache: pip
python: 3.7
services:
- docker

env:
  global:
  - DOCS_DEPLOY_BRANCH: env-branch
  - REPO: sbellem/HoneyBadgerMPC

stages:
- name: One
- name: Two
  if: branch = env(DOCS_DEPLOY_BRANCH)
- name: Three
  if: |
    repo = sbellem/HoneyBadgerMPC AND \
    type = push AND \
    branch = env(DOCS_DEPLOY_BRANCH)

jobs:
  include:
  - stage: One
    install: skip
    script: echo "Stage One"
  - stage: Two
    install: skip
    script: echo "Stage Two -- depends on env()"
  - stage: Three
    install: skip
    script: echo "Stage Three -- depends on env()"
  - if: |
      type = pul_request OR \
      repo = initc3/HoneyBadgerMPC OR \
      branch = env(DOCS_DEPLOY_BRANCH)
    name: Job that depends on env func
    install: skip
    script: echo "Job that depends on env()"
  - stage: Deploy stage
    install: skip
    script: echo "Stage for which the deploy phase depends on env()"
    after_success: .ci/copy-docs-from-container.sh
    deploy:
      skip_cleanup: true
      provider: script
      script: echo "Depends on env()"
      # Redundant with stage condition; consider removing or keep for extra protection?
      on:
        repo: env(REPO)
        branch: env(DOCS_DEPLOY_BRANCH)
        type: push
