os: linux
dist: bionic
language: python
cache: pip
python: 3.7
services:
- docker

env:
  global:
  - SOMEBRANCH: "env-branch"

stages:
- name: One
  if: branch = "env-branch"
- name: Two
  if: branch = env(SOMEBRANCH)

jobs:
  include:
  - stage: One
    install: skip
    script: echo "Stage One depends on env()"
  - stage: Two
    name: Job Zero
    install: skip
    script: echo "Stage Two does NOT depend on env()"
  - if: branch = env(SOMEBRANCH)
    name: Job One
    install: skip
    script: echo "Job One depends on env()"
  - if: branch = "env-branch"
    name: Job Two
    install: skip
    script: echo "Job Two does NOT depend on env()"
