os: linux
dist: xenial
language: python
python: 3.7
sudo: true

services:
  - docker

env:
  global:
    - DOCS_DEPLOY_KEY_LABEL: 63cc0c40c9de

matrix:
  include:
    - env: BUILD=tests
    - env: BUILD=flake8
    - env: BUILD=docs

install:  .ci/travis-install.sh

script: .ci/travis-script.sh

after_success: .ci/travis-after-success.sh

deploy:
  skip_cleanup: true
  provider: script
  script: .ci/travis-publish-docs.sh
  on:
    branch: docs-on-github-pages
    condition: '"${BUILD}" == *docs*'
