n = 4
t = 1
deployer_address = "0x1eEEABdB4c6e58BacafeBE0ED590Db059f574C61"
[[peers]]
id = 0
host = "hbmpc.peer0.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x10147c343a34a8BF27Aa359e473f11b2B15Af33c"

[[peers]]
id = 1
host = "hbmpc.peer1.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x5Dfe73DCBB40b382b9209d1C8618f07606607d47"

[[peers]]
id = 2
host = "hbmpc.peer2.io"
http_port = 8080
mpc_port = 7000
eth_address = "0xbD95D7Cb536f62052825ABB7a5302E531ec0C51b"

[[peers]]
id = 3
host = "hbmpc.peer3.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x3Ab53C965D394681c5c6a78FC3A6762766C9f85c"

[eth]
rpc_host = "eth.blockchain.io"
rpc_port = 8545

[contract]
path = "~/.coordinator/contract.rl"
lang = "ratel"
name = "MpcCoordinator"
address = "0xCbA98Bd1af1965475529121Cd590C7519aca4214"
