version: '3.7'

services:
  blockchain:
    container_name: blockchain
    image: trufflesuite/ganache-cli
    command: --accounts 50 --blockTime 1 > acctKeys.json 2>&1
  mpc-simulation:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../honeybadgermpc:/usr/src/honeybadgermpc/honeybadgermpc
    depends_on:
      - blockchain
    command: ["./apps/wait-for-it.sh", "blockchain:8545", "--", "python", "apps/masks/simulation.py"]
