version: '3.7'

services:
  eth.blockchain.io:
    container_name: eth.blockchain.io
    image: trufflesuite/ganache-cli
    command: --accounts 50 --blockTime 1 > acctKeys.json 2>&1
  hbmpc.coordinator.io:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../apps/masks/configs/hbmpc.coordinator.io.toml:/root/.hbmpc.toml
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - eth.blockchain.io
    command: ["./apps/wait-for-it.sh", "eth.blockchain.io:8545", "--", "python", "apps/masks/coordinator.py"]
  hbmpc.peer0.io:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../apps/masks/configs/hbmpc.peer0.io.toml:/root/.hbmpc.toml
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - hbmpc.coordinator.io
    command: ["./apps/wait-for-it.sh", "eth.blockchain.io:8545", "--", "python", "apps/masks/mpcserver.py", "--config-file", "~/.hbmpc.toml"]
  hbmpc.peer1.io:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../apps/masks/configs/hbmpc.peer1.io.toml:/root/.hbmpc.toml
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - hbmpc.coordinator.io
    command: ["./apps/wait-for-it.sh", "eth.blockchain.io:8545", "--", "python", "apps/masks/mpcserver.py", "--config-file", "~/.hbmpc.toml"]
  hbmpc.peer2.io:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../apps/masks/configs/hbmpc.peer2.io.toml:/root/.hbmpc.toml
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - hbmpc.coordinator.io
    command: ["./apps/wait-for-it.sh", "eth.blockchain.io:8545", "--", "python", "apps/masks/mpcserver.py", "--config-file", "~/.hbmpc.toml"]
  hbmpc.peer3.io:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../apps/masks/configs/hbmpc.peer3.io.toml:/root/.hbmpc.toml
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - hbmpc.coordinator.io
    command: ["./apps/wait-for-it.sh", "eth.blockchain.io:8545", "--", "python", "apps/masks/mpcserver.py", "--config-file", "~/.hbmpc.toml"]
  hbmpc.client.io:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../apps/masks/configs/hbmpc.client.io.toml:/root/.hbmpc.toml
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - hbmpc.peer3.io
    command: ["./apps/wait-for-it.sh", "--port", "8080", "--", "python", "apps/masks/client.py", "--config-file", "~/.hbmpc.toml"]
