version: '3.7'

services:
  blockchain:
    container_name: blockchain
    image: trufflesuite/ganache-cli
    command: --accounts 50 --blockTime 1 > acctKeys.json 2>&1
  setup:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - blockchain
    command: ["./apps/wait-for-it.sh", "blockchain:8545", "--", "python", "apps/masks/setup_phase.py"]
  mpc_server_0:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../apps/masks/configs/server_0.toml:/root/.hbmpc.toml
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - setup
    command: ["./apps/wait-for-it.sh", "blockchain:8545", "--", "python", "apps/masks/mpcserver.py", "--config-file", "~/.hbmpc.toml"]
  mpc_server_1:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../apps/masks/configs/server_1.toml:/root/.hbmpc.toml
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - setup
    command: ["./apps/wait-for-it.sh", "blockchain:8545", "--", "python", "apps/masks/mpcserver.py", "--config-file", "~/.hbmpc.toml"]
  mpc_server_2:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../apps/masks/configs/server_2.toml:/root/.hbmpc.toml
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - setup
    command: ["./apps/wait-for-it.sh", "blockchain:8545", "--", "python", "apps/masks/mpcserver.py", "--config-file", "~/.hbmpc.toml"]
  mpc_server_3:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../apps/masks/configs/server_3.toml:/root/.hbmpc.toml
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - setup
    command: ["./apps/wait-for-it.sh", "blockchain:8545", "--", "python", "apps/masks/mpcserver.py", "--config-file", "~/.hbmpc.toml"]
  client:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - mpcnet
    command: ["./apps/wait-for-it.sh", "mpcnet:8083", "--", "python", "apps/masks/client.py"]
