n = 4
t = 1
deployer_address = "0x33e18BA6929eD1fC8998C5162688c1Ba8b70f1da"
[[peers]]
id = 0
host = "hbmpc.peer0.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x9E2FC27f825FbA0796b1404836f9d9BC3eeEa6df"

[[peers]]
id = 1
host = "hbmpc.peer1.io"
http_port = 8080
mpc_port = 7000
eth_address = "0xcE39684A14855eB177246bD2764Bef6FEB3f0bbe"

[[peers]]
id = 2
host = "hbmpc.peer2.io"
http_port = 8080
mpc_port = 7000
eth_address = "0xEd8e524717Db1b48aEfcAB80c7D44764fC7b2708"

[[peers]]
id = 3
host = "hbmpc.peer3.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x309a4479C411Fe4933fdbd32eBAEc25e92a13247"

[eth]
rpc_host = "eth.blockchain.io"
rpc_port = 8545

[contract]
path = "~/.coordinator/contract.sol"
name = "MpcCoordinator"
address = "0xCda11109df13FE22ba0C89713556dc3b545C7016"
