n = 4
t = 1
deployer_address = "0xaEc573E24C1FC4f01667EC63A568309B1C2FE7Ee"
[[peers]]
id = 0
host = "hbmpc.peer0.io"
http_port = 8080
mpc_port = 7000
eth_address = "0xBc40a417f93989cCCF543a7711CA78eaad205aED"

[[peers]]
id = 1
host = "hbmpc.peer1.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x76388CD554E60e14B270c6eA54F5b2F8f87D0144"

[[peers]]
id = 2
host = "hbmpc.peer2.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x70636f2F908F0b0A885EC13Ade9488c9Bdc6142B"

[[peers]]
id = 3
host = "hbmpc.peer3.io"
http_port = 8080
mpc_port = 7000
eth_address = "0xCC17036D413e7072aa6fA2F9fC7a5b039e96A36b"

[eth]
rpc_host = "eth.blockchain.io"
rpc_port = 8545

[contract]
path = "~/.coordinator/contract.sol"
name = "MpcCoordinator"
address = "0x10F3880e9DbE76F31Eca073Ba5387d1ccB949A5c"
