# MPC server configuation

# the context is used to evaluate relative file paths
context = "."

id = 0
host = "hbmpc.peer0.io"
port = 8080
dr_port = 7000

# MPC network params
n = 4
t = 1

# Ethereum blockchain
[eth]
rpc_host = "eth.blockchain.io"
rpc_port = 8545

# contract
# the contract file path can be relative or absolute
contract_path = "contract.sol"
contract_name = "MpcCoordinator"
public_data_dir = "public-data"

# MPC peers 
[[peers]]
id = 1
host = "hbmpc.peer1.io"
port = 8080
dr_port = 7000

[[peers]]
id = 2
host = "hbmpc.peer2.io"
port = 8080
dr_port = 7000

[[peers]]
id = 3
host = "hbmpc.peer3.io"
port = 8080
dr_port = 7000
