n = 4
t = 1
deployer_address = "0x3a6c43549b40D93bf3Da2714DaDCa09991A2FFcb"
[[peers]]
id = 0
host = "hbmpc.peer0.io"
http_port = 8080
mpc_port = 7000
eth_address = "0xa96C72625084c5acDF0e9b98722f0e2a9E18abff"

[[peers]]
id = 1
host = "hbmpc.peer1.io"
http_port = 8080
mpc_port = 7000
eth_address = "0xe8AE75406347661499615cc6a4235f50dD65f401"

[[peers]]
id = 2
host = "hbmpc.peer2.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x9671BF2BF8de14BDc2EF6C8c1d2DA72A0013651C"

[[peers]]
id = 3
host = "hbmpc.peer3.io"
http_port = 8080
mpc_port = 7000
eth_address = "0xD2b2334018Fdc3CdA1F615B4171196C68EA70Cc6"

[eth]
rpc_host = "eth.blockchain.io"
rpc_port = 8545

[contract]
path = "~/.coordinator/contract.rl"
lang = "ratel"
name = "MpcCoordinator"
address = "0xF6Da10FBD6aC45b4520421Fb323087bD2c12f4C1"
