n = 4
t = 1
deployer_address = "0x8cF127E04d835FAf1b820FacFE62454424CBb6d7"
[[peers]]
id = 0
host = "hbmpc.peer0.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x1fcCf25FED050a23cD7349d7260EB012fd784E38"

[[peers]]
id = 1
host = "hbmpc.peer1.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x95B4C0B77d7bE61B4B24d5598566e3d4C6479b75"

[[peers]]
id = 2
host = "hbmpc.peer2.io"
http_port = 8080
mpc_port = 7000
eth_address = "0xb2c04F79CDdF78a7d3256003989c0b206Db0CF70"

[[peers]]
id = 3
host = "hbmpc.peer3.io"
http_port = 8080
mpc_port = 7000
eth_address = "0xbBFcaAB242531667bc244DADe3A3c053b5f3c545"

[eth]
rpc_host = "eth.blockchain.io"
rpc_port = 8545

[contract]
path = "~/.coordinator/contract.rl"
lang = "ratel"
name = "MpcCoordinator"
address = "0x81e96D85d17625d7b5cA013c3bA8eC0de4e93666"
