n = 4
t = 1
deployer_address = "0xaF1d53e6cb190E5007255cA2555B86ad5eED976e"
[[peers]]
id = 0
host = "hbmpc.peer0.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x5846e7eE34033bdDB7AEb64d0A3777909Fc0ED7d"

[[peers]]
id = 1
host = "hbmpc.peer1.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x63Fa71A5f1468c6ef85fCC705e1bf1cc8aC6D88A"

[[peers]]
id = 2
host = "hbmpc.peer2.io"
http_port = 8080
mpc_port = 7000
eth_address = "0xa35D2Cb936e5D7E9B080Cda0bf8304cefEA56557"

[[peers]]
id = 3
host = "hbmpc.peer3.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x34bE30E8ccd9f504398d708Bf97E6328b86FDC01"

[eth]
rpc_host = "eth.blockchain.io"
rpc_port = 8545

[contract]
path = "~/.coordinator/contract.sol"
name = "MpcCoordinator"
address = "0x0997775df853b6C13782bbB6981a33283b0a1eA8"
