n = 4
t = 1
deployer_address = "0x68E341fb707267858103131F4986d1C54d9f0751"
[[peers]]
id = 0
host = "hbmpc.peer0.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x4835032797aF3e85eFDC9047292Be285F3cF0eFC"

[[peers]]
id = 1
host = "hbmpc.peer1.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x98a76A0016f88eDA0F1a66EDdc43DF95E463DB35"

[[peers]]
id = 2
host = "hbmpc.peer2.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x68A94b8C0FE244afCF7eA3CCFEDec0db2BbcD0D4"

[[peers]]
id = 3
host = "hbmpc.peer3.io"
http_port = 8080
mpc_port = 7000
eth_address = "0x4a031e756d6915C993bF9aA60d35b49C58D1698F"

[eth]
rpc_host = "eth.blockchain.io"
rpc_port = 8545

[contract]
path = "~/.coordinator/contract.rl"
lang = "ratel"
name = "MpcCoordinator"
address = "0xA570B93021cbBb68BF646FB0bEE4529f1602Ac1e"
